function changFigureColor(XData1, YData1)
%CREATEFIGURE(XDATA1, YDATA1)
%  XDATA1:  line xdata
%  YDATA1:  line ydata

%  Auto-generated by MATLAB on 26-Jun-2017 12:51:20

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);

% Create line
line(XData1,YData1,'Parent',axes1,'Color',[1 0 0]);

% Create xlabel
xlabel('Frequency (Hz)');

% Create title
title('Welch Power Spectral Density Estimate');

% Create ylabel
ylabel('Power/frequency (dB/Hz)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 140]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
