function cleanData = notch150Hz_v2(currData,srate,Fstop1,Fstop2)
%NOTCH105_V2HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 27-Sep-2018 10:52:16

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = srate;  % Sampling Frequency

Fpass1 = 145;             % First Passband Frequency
% Fstop1 = 102;             % First Stopband Frequency
% Fstop2 = 110;             % Second Stopband Frequency
Fpass2 = 170;             % Second Passband Frequency
Dpass1 = 0.028774368332;  % First Passband Ripple
Dstop  = 0.001;           % Stopband Attenuation
Dpass2 = 0.057501127785;  % Second Passband Ripple
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass1 Fstop1 Fstop2 Fpass2]/(Fs/2), [1 0 ...
                          1], [Dpass1 Dstop Dpass2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);
cleanData = filter(Hd,currData)

% [EOF]
